### ISSUE TITLE
milestone 03 feedback

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/524_Rmarcelle_paul_socorro#27]
Hi,

Thanks for your efforts in milestone 03 submission. I've just reviewed your submission and I have few comments/suggestions below.

- [x] Your package installation runs without any problems 
- [x] You have provided very comprehensive test cases that I cannot think of any more 
- [x] You have provided a vignette for the R package 
- [x] You have provided an open source license 
- [x] You have provided good documentation of your function
- [x] You provided your branch coverage results

Thanks!

**Comment by mchiriboga** [comment]
Thanks for the feedback, Hossam.
